// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:qr21/data/models/hive_adapters/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(QrDataAdapter());
    registerAdapter(RocketChatCredsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(QrDataAdapter());
    registerAdapter(RocketChatCredsAdapter());
  }
}
